# Generated by Django 4.2.26 on 2025-11-13 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='leituras.contador')),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=12)),
                ('flow_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], default='automatic', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='leituras.contador')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras', to='leituras.device')),
            ],
            options={
                'indexes': [models.Index(fields=['contador', 'captured_at'], name='leituras_le_contado_e5cd29_idx')],
            },
        ),
    ]
