# Generated by Django 4.2 on 2025-12-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0001_initial'),
    ]

    operations = [
    ]
